version: '2'
services:
 nginx:
   build: 
     context: ./nginx
     args: 
         useruid: $USERID
   volumes_from: ['fpm:ro']
   ports: ['127.0.0.1:65004:80']
 fpm:
   build: 
     context: ./php
     args:
       useruid: $USERID
   volumes: ['./wiki:/var/www:rw']
   command: sh -c "chown -R nginx-php:nginx-php ./ ; php-fpm"
#volumes:
#     wiki:
